apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: myproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: mycontainer
        image: mehar221/myproject1:latest
        ports:
        - containerPort: 80
