apiVersion: v1
kind: Service
metadata:
  name: myproject1-service
spec:
  type: NodePort
  selector:
    app: myproject
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80 
      nodePort: 30000 
